import json
import re

questions_list = [
    (1, "Select all columns from a table"),
    (2, "Select specific columns"),
    (3, "Filter rows using WHERE"),
    (4, "Use multiple conditions with AND"),
    (5, "Use multiple conditions with OR"),
    (6, "Use NOT"),
    (7, "Use BETWEEN"),
    (8, "Use IN"),
    (9, "Use NOT IN"),
    (10, "Use LIKE"),
    (11, "Find records starting with a letter"),
    (12, "Find records ending with a letter"),
    (13, "Find records containing a word"),
    (14, "Use IS NULL"),
    (15, "Use IS NOT NULL"),
    (16, "Sort using ORDER BY ASC"),
    (17, "Sort using ORDER BY DESC"),
    (18, "Retrieve top N records (LIMIT/TOP)"),
    (19, "Remove duplicates using DISTINCT"),
    (20, "Alias columns using AS"),
    (21, "Count total rows"),
    (22, "Count distinct values"),
    (23, "Find maximum salary"),
    (24, "Find minimum salary"),
    (25, "Find average salary"),
    (26, "Find total salary"),
    (27, "Find average marks"),
    (28, "Sum sales"),
    (29, "Count employees in each department"),
    (30, "Find department with highest salary"),
    (31, "Find department with lowest salary"),
    (32, "Average salary by department"),
    (33, "Maximum marks by class"),
    (34, "Minimum sales by region"),
    (35, "Total revenue by month"),
    (36, "Group employees by department"),
    (37, "Group students by class"),
    (38, "Count employees per department"),
    (39, "Departments having more than 5 employees"),
    (40, "Departments with average salary > 50,000"),
    (41, "Cities having more than 10 customers"),
    (42, "Product categories with highest sales"),
    (43, "Customers with more than 5 orders"),
    (44, "Branches with highest profit"),
    (45, "States with highest customers"),
    (46, "Monthly sales summary"),
    (47, "Yearly sales summary"),
    (48, "Products sold more than 100 times"),
    (49, "Average age by city"),
    (50, "Highest salary department"),
    (51, "Lowest salary department"),
    (52, "Average marks above 80"),
    (53, "Groups using multiple columns"),
    (54, "HAVING with COUNT"),
    (55, "HAVING with SUM"),
    (56, "Inner Join"),
    (57, "Left Join"),
    (58, "Right Join"),
    (59, "Full Join"),
    (60, "Self Join"),
    (61, "Cross Join"),
    (62, "Employees with department names"),
    (63, "Customers with orders"),
    (64, "Customers without orders"),
    (65, "Orders without customers"),
    (66, "Students with course names"),
    (67, "Employees without managers"),
    (68, "Manager and employee names"),
    (69, "Multiple table joins"),
    (70, "Join three tables"),
    (71, "Join four tables"),
    (72, "Highest order per customer"),
    (73, "Total orders per customer"),
    (74, "Employee and project details"),
    (75, "Product and supplier details"),
    (76, "Customer-city join"),
    (77, "Find unmatched rows"),
    (78, "Sales with product names"),
    (79, "Student-course enrollment"),
    (80, "Employee-manager hierarchy"),
    (81, "Left join with WHERE"),
    (82, "Right join with NULL"),
    (83, "Join with GROUP BY"),
    (84, "Join with HAVING"),
    (85, "Join with aggregate functions"),
    (86, "Join with CASE"),
    (87, "Join with subquery"),
    (88, "Join using aliases"),
    (89, "Difference between INNER and LEFT JOIN"),
    (90, "Difference between LEFT and RIGHT JOIN"),
    (91, "Salary above average"),
    (92, "Second highest salary"),
    (93, "Third highest salary"),
    (94, "Nth highest salary"),
    (95, "Employees earning more than department average"),
    (96, "Products above average price"),
    (97, "Customers with maximum orders"),
    (98, "Employees in highest-paying department"),
    (99, "Departments with highest average salary"),
    (100, "Find duplicate rows"),
    (101, "Remove duplicate rows"),
    (102, "Exists vs IN"),
    (103, "NOT EXISTS"),
    (104, "Correlated subquery"),
    (105, "Nested subqueries"),
    (106, "Max salary employee"),
    (107, "Min salary employee"),
    (108, "Customers without orders"),
    (109, "Products never sold"),
    (110, "Orders above average amount"),
    (111, "ROW_NUMBER()"),
    (112, "RANK()"),
    (113, "DENSE_RANK()"),
    (114, "NTILE()"),
    (115, "LEAD()"),
    (116, "LAG()"),
    (117, "FIRST_VALUE()"),
    (118, "LAST_VALUE()"),
    (119, "Running total"),
    (120, "Cumulative sum"),
    (121, "Moving average"),
    (122, "Top 3 salaries"),
    (123, "Highest salary per department"),
    (124, "Lowest salary per department"),
    (125, "Previous month's sales"),
    (126, "Next month's sales"),
    (127, "Difference from previous row"),
    (128, "Running average"),
    (129, "Running count"),
    (130, "Percent rank"),
    (131, "Dense rank by department"),
    (132, "Row number partition"),
    (133, "Ranking products"),
    (134, "Ranking students"),
    (135, "Ranking salespersons"),
    (136, "Top N customers"),
    (137, "Bottom N products"),
    (138, "Window frame examples"),
    (139, "PARTITION BY"),
    (140, "ORDER BY in window functions"),
    (141, "Simple CTE"),
    (142, "Multiple CTEs"),
    (143, "Recursive CTE"),
    (144, "Employee hierarchy"),
    (145, "Category hierarchy"),
    (146, "Running totals using CTE"),
    (147, "Ranking using CTE"),
    (148, "Duplicate removal"),
    (149, "Temporary calculations"),
    (150, "Monthly sales report"),
    (151, "Department summary"),
    (152, "Customer summary"),
    (153, "Sales analysis"),
    (154, "Employee analysis"),
    (155, "Recursive numbers"),
    (156, "Grade students"),
    (157, "Salary bands"),
    (158, "Age groups"),
    (159, "Sales categories"),
    (160, "Bonus calculation"),
    (161, "Customer classification"),
    (162, "Pass/Fail status"),
    (163, "Gender formatting"),
    (164, "Conditional aggregation"),
    (165, "Multiple CASE conditions"),
    (166, "LENGTH()"),
    (167, "UPPER()"),
    (168, "LOWER()"),
    (169, "CONCAT()"),
    (170, "SUBSTRING()"),
    (171, "REPLACE()"),
    (172, "TRIM()"),
    (173, "LTRIM()"),
    (174, "RTRIM()"),
    (175, "LEFT()"),
    (176, "RIGHT()"),
    (177, "POSITION/CHARINDEX()"),
    (178, "REVERSE()"),
    (179, "Split names"),
    (180, "Initials"),
    (181, "Email extraction"),
    (182, "Domain extraction"),
    (183, "Count characters"),
    (184, "Remove spaces"),
    (185, "Replace multiple characters"),
    (186, "Current date"),
    (187, "Current timestamp"),
    (188, "Difference between dates"),
    (189, "Add days"),
    (190, "Add months"),
    (191, "Extract year"),
    (192, "Extract month"),
    (193, "Extract day"),
    (194, "Week number"),
    (195, "Quarter"),
    (196, "Last day of month"),
    (197, "First day of month"),
    (198, "Date formatting"),
    (199, "Age calculation"),
    (200, "Employees hired this year"),
    (201, "Orders this month"),
    (202, "Sales last 30 days"),
    (203, "Weekend records"),
    (204, "Leap year check"),
    (205, "Monthly report"),
    (206, "Find duplicates"),
    (207, "Remove duplicates"),
    (208, "Duplicate emails"),
    (209, "Duplicate names"),
    (210, "Duplicate phone numbers"),
    (211, "Duplicate salaries"),
    (212, "Keep first duplicate"),
    (213, "Keep latest duplicate"),
    (214, "Delete duplicate rows"),
    (215, "Count duplicate groups"),
    (216, "Second highest salary"),
    (217, "Nth highest salary"),
    (218, "Top 3 salaries per department"),
    (219, "Consecutive login days"),
    (220, "Consecutive numbers"),
    (221, "Gap and island problems"),
    (222, "Median salary"),
    (223, "Pivot table"),
    (224, "Unpivot table"),
    (225, "Employee hierarchy"),
    (226, "Running balance"),
    (227, "Daily active users"),
    (228, "Monthly active users"),
    (229, "Churn customers"),
    (230, "Repeat customers"),
    (231, "First purchase"),
    (232, "Last purchase"),
    (233, "Most expensive product"),
    (234, "Least expensive product"),
    (235, "Product never sold"),
    (236, "Customer lifetime value"),
    (237, "Revenue by month"),
    (238, "Rolling average"),
    (239, "Year-over-year growth"),
    (240, "Month-over-month growth"),
    (241, "Top-selling product"),
    (242, "Least-selling product"),
    (243, "Market share calculation"),
    (244, "Percent contribution"),
    (245, "Cohort analysis"),
    (246, "Retention analysis"),
    (247, "Dense ranking challenge"),
    (248, "Recursive hierarchy"),
    (249, "Sessionization problem"),
    (250, "Fraud detection using SQL")
]

def get_chapter(num):
    if num <= 20: return (1, 'Module 1: Basic SQL (Questions 1-20)')
    if num <= 35: return (2, 'Module 2: Aggregate Functions (Questions 21-35)')
    if num <= 55: return (3, 'Module 3: GROUP BY & HAVING (Questions 36-55)')
    if num <= 90: return (4, 'Module 4: Joins (Questions 56-90)')
    if num <= 110: return (5, 'Module 5: Subqueries (Questions 91-110)')
    if num <= 140: return (6, 'Module 6: Window Functions (Questions 111-140)')
    if num <= 155: return (7, 'Module 7: CTE (Common Table Expressions) (Questions 141-155)')
    if num <= 165: return (8, 'Module 8: CASE Statements (Questions 156-165)')
    if num <= 185: return (9, 'Module 9: String Functions (Questions 166-185)')
    if num <= 205: return (10, 'Module 10: Date Functions (Questions 186-205)')
    if num <= 215: return (11, 'Module 11: Duplicates (Questions 206-215)')
    return (12, 'Module 12: Advanced SQL (Questions 216-250)')

challenges = []
for num, title in questions_list:
    ch_id, ch_title = get_chapter(num)
    
    starter = f'-- Problem #{num}: {title}\n-- Write your SQL query below\n\n'

    ch_obj = {
        'level_number': num,
        'chapter_id': ch_id,
        'chapter_title': ch_title,
        'title': title,
        'story': f'SQL Practice Challenge #{num}: Master {title} in data querying and database engineering.',
        'objective': f'Write an ANSI SQL query to perform: {title}. Execute query to verify column schema and record output.',
        'starter_code': starter,
        'expected_output': 'employee_id | first_name | last_name',
        'hints': [f'Use standard SQL syntax for {title}.', 'Check sample tables: employees, departments, customers, orders, products, students.'],
        'test_cases': [
            {'input': '', 'expected': 'employee_id | first_name | last_name', 'hidden': False, 'description': f'Test Case 1: {title}'}
        ],
        'explanation': f'SQL query for {title} executes relational algebra operations against target tables.',
        'xp_reward': 60 + (num % 40),
        'coin_reward': 15 + (num % 10),
        'is_boss': (num % 10 == 0),
        'boss_name': f'SQL Boss #{num // 10}' if (num % 10 == 0) else None,
        'boss_hp': 100 + num if (num % 10 == 0) else None,
        'difficulty': 'Easy' if num <= 55 else ('Medium' if num <= 155 else 'Hard')
    }
    challenges.append(ch_obj)

with open('/Users/spidey./Desktop/Study/backend/app/sql_challenges_seeded.json', 'w') as f:
    json.dump(challenges, f, indent=2)

print('Generated 250 SQL challenges successfully!')
